services:
  - type: web
    name: proyecto-grado
    env: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn==23.0.0
    startCommand: python -m gunicorn "app:create_app()"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
